# -*- coding: utf-8 -*-
def patch(path, pairs):
    with open(path, 'rb') as f:
        s = f.read().decode('utf-8')
    changes = 0
    misses = []
    for old, new in pairs:
        if old in s:
            s = s.replace(old, new, 1)
            changes += 1
        else:
            misses.append(old[:90])
    with open(path, 'wb') as f:
        f.write(s.encode('utf-8'))
    print(f"{path}: {changes}/{len(pairs)}")
    for m in misses:
        print("  MISS:", m)

patch(r'c:/Users/cyril/Project/NuvoraStudioWeb/src/pages/fr/realisations/index.astro', [
    ("title: 'Un fabricant japonais de lits médicaux cherchait des distributeurs en Europe. LinkedIn a fait le reste.',",
     "title: \"Un fabricant japonais de lits médicaux cherchait des distributeurs en Europe. LinkedIn s'est chargé du reste.\","),
    ("subtitle: 'Aucune présence en dehors du Japon. 90 jours plus tard, les premiers distributeurs européens étaient en discussion.',",
     "subtitle: \"Aucune présence hors du Japon au départ. 90 jours plus tard, les premiers distributeurs européens étaient déjà en discussion.\","),
    ("services: ['Contenu LinkedIn', 'Publicité LinkedIn', 'Visibilité du dirigeant'],",
     "services: ['Contenu LinkedIn', 'Publicité LinkedIn', 'Visibilité du dirigeant'],"),
    ("title: '40 ingénieurs d\\'un câblier chinois sont devenus porte-parole de la marque sur LinkedIn.',",
     "title: \"40 ingénieurs d'un câblier chinois sont devenus les porte-parole de la marque sur LinkedIn.\","),
    ("subtitle: 'Une entreprise mondiale, mais personne ne publiait sur LinkedIn. 60 jours après, c\\'était une autre histoire.',",
     "subtitle: \"Un groupe mondial, mais zéro publication sur LinkedIn. 60 jours plus tard, l'histoire avait changé.\","),
    ("services: ['Contenu LinkedIn', 'Mobilisation des équipes', 'Formation'],",
     "services: ['Contenu LinkedIn', 'Employés ambassadeurs', 'Formation'],"),
    ("title: 'Comment un fabricant suédois de polymères est devenu le nom que les acheteurs aéronautiques tapent en premier.',",
     "title: \"Comment un fabricant suédois de polymères est devenu le premier nom que tapent les acheteurs de l'aéronautique.\","),
    ("subtitle: 'Des matériaux de classe mondiale, une page LinkedIn qui ne racontait rien. On a corrigé ça.',",
     "subtitle: \"Des matériaux de classe mondiale, une page LinkedIn qui ne racontait rien. On a remis tout ça en place.\","),
    ("title: 'Un labo de parfums français a décroché des contrats luxe grâce à la voix de sa fondatrice sur LinkedIn.',",
     "title: \"Un labo de parfums français a décroché des contrats du luxe grâce à la voix de sa fondatrice sur LinkedIn.\","),
    ("subtitle: 'Les courriels de prospection restaient sans réponse. Un profil LinkedIn bien travaillé a tout changé.',",
     "subtitle: \"Les e-mails de prospection restaient sans réponse. Un profil LinkedIn bien travaillé a tout débloqué.\","),
    ("services: ['Visibilité du dirigeant', 'Contenu LinkedIn', 'Conseil'],",
     "services: ['Visibilité du dirigeant', 'Contenu LinkedIn', 'Conseil'],"),
    ("title: 'Quand les associés d\\'un cabinet comptable se mettent à publier sur LinkedIn, les prospects suivent.',",
     "title: \"Quand les associés d'un cabinet comptable se mettent à publier sur LinkedIn, les prospects suivent.\","),
    ("subtitle: '12 associés, aucun actif sur LinkedIn. Trois mois plus tard, six publiaient toutes les semaines.',",
     "subtitle: \"12 associés, aucun actif sur LinkedIn. Trois mois plus tard, six publiaient chaque semaine.\","),
    ("services: ['Contenu LinkedIn', 'Formation', 'Publicité LinkedIn'],",
     "services: ['Contenu LinkedIn', 'Formation', 'Publicité LinkedIn'],"),
    ("title: 'Des avocats hongkongais devenus incontournables sur les dossiers transfrontaliers, grâce à LinkedIn.',",
     "title: \"Des avocats hongkongais devenus incontournables sur les dossiers transfrontaliers. Grâce à LinkedIn.\","),
    ("subtitle: 'L\\'expertise, ils l\\'avaient. Ce qui manquait c\\'était la visibilité.',",
     "subtitle: \"L'expertise, ils l'avaient. Ce qui leur manquait, c'était la visibilité.\","),
    ("services: ['Visibilité du dirigeant', 'Contenu LinkedIn', 'Mobilisation des équipes'],",
     "services: ['Visibilité du dirigeant', 'Contenu LinkedIn', 'Employés ambassadeurs'],"),
    ("{ value: '9', label: 'Démos produit réservées' }",
     "{ value: '9', label: 'Démos produit réservées' }"),
    ("{ value: '74', label: 'Prospects qualifiés' }",
     "{ value: '74', label: 'Prospects qualifiés' }"),
    ("{ value: '52 $', label: 'Coût par prospect' }",
     "{ value: '52 $', label: 'Coût par prospect' }"),
    ("{ value: '40', label: 'Personnes embarquées' }",
     "{ value: '40', label: 'Collaborateurs embarqués' }"),
    ("{ value: '160K', label: 'Vues en 60 jours' }",
     "{ value: '160K', label: 'Vues en 60 jours' }"),
    ("{ value: '1 400', label: 'Abonnés à la page' }",
     "{ value: '1 400', label: 'Nouveaux abonnés' }"),
    ("{ value: '1 900', label: 'Nouveaux abonnés' }",
     "{ value: '1 900', label: 'Nouveaux abonnés' }"),
    ("{ value: '3,2 %', label: 'Taux d\\'interaction' }",
     "{ value: '3,2 %', label: \"Taux d'engagement\" }"),
    ("{ value: '61', label: 'Prospects générés' }",
     "{ value: '61', label: 'Prospects générés' }"),
    ("{ value: '2 400', label: 'Abonnés en 4 mois' }",
     "{ value: '2 400', label: 'Abonnés en 4 mois' }"),
    ("{ value: '8 000+', label: 'Vues meilleure publication' }",
     "{ value: '8 000+', label: 'Vues du meilleur post' }"),
    ("{ value: '2', label: 'Demandes entrantes' }",
     "{ value: '2', label: 'Demandes entrantes' }"),
    ("{ value: '6/12', label: 'Associés actifs chaque semaine' }",
     "{ value: '6/12', label: 'Associés actifs chaque semaine' }"),
    ("{ value: '42', label: 'Prospects générés' }",
     "{ value: '42', label: 'Prospects générés' }"),
    ("{ value: '38 $', label: 'Coût par prospect' }",
     "{ value: '38 $', label: 'Coût par prospect' }"),
    ("{ value: '2', label: 'Mandats décrochés via LinkedIn' }",
     "{ value: '2', label: 'Mandats décrochés via LinkedIn' }"),
    ("{ value: '3 800', label: 'Abonnés cumulés' }",
     "{ value: '3 800', label: 'Abonnés cumulés' }"),
    ("{ value: '12K', label: 'Vues meilleure publication' }",
     "{ value: '12K', label: 'Vues du meilleur post' }"),
    ("title=\"Réalisations | Études de cas | Nuvora Studio\"",
     "title=\"Réalisations | Études de cas | Nuvora Studio\""),
    ("description=\"Des résultats concrets obtenus pour des clients réels. Comment on aide les entreprises B2B à se développer sur LinkedIn : contenu, publicité, visibilité des dirigeants, mobilisation des équipes.\"",
     "description=\"Des résultats concrets, obtenus pour de vrais clients. Comment on aide les entreprises B2B à se développer sur LinkedIn : contenu, publicité, visibilité des dirigeants, employés ambassadeurs.\""),
    ("abstract=\"Études de cas Nuvora Studio. Des stratégies LinkedIn qui se traduisent en résultats commerciaux.\"",
     "abstract=\"Études de cas Nuvora Studio. Des stratégies LinkedIn qui se transforment en résultats commerciaux.\""),
    ("Des clients réels, des stratégies documentées et des chiffres qu'on peut vérifier. On n'invente rien.",
     "De vrais clients, des stratégies documentées et des chiffres qu'on peut vérifier. On n'invente rien."),
    ("Aucune étude de cas pour ce service.",
     "Aucune étude de cas pour ce service pour le moment."),
    ("On ne fait pas que donner des conseils.<br />On applique ce qu'on dit.",
     "On ne se contente pas de donner des conseils.<br />On applique ce qu'on prêche."),
    ("Cyril Drouin, fondateur de Nuvora Studio, entretient exactement le genre de présence LinkedIn qu'on construit pour nos clients. C'est pas une page vitrine, c'est un vrai profil qui génère des échanges et qui montre concrètement ce qu'on sait faire.",
     "Cyril Drouin, fondateur de Nuvora Studio, tient exactement le genre de présence LinkedIn qu'on construit pour nos clients. Pas une vitrine figée : un vrai profil qui génère des échanges et qui montre, en pratique, ce qu'on sait faire."),
    ("Voir le profil de Cyril sur LinkedIn",
     "Découvrir le profil LinkedIn de Cyril"),
    ("Capture d'écran du profil LinkedIn de Cyril Drouin",
     "Capture d'écran du profil LinkedIn de Cyril Drouin"),
    ("<span class=\"founder-card__profile-role\">Fondateur et directeur général, Nuvora Studio</span>",
     "<span class=\"founder-card__profile-role\">Fondateur et directeur général, Nuvora Studio</span>"),
    ("Voir le profil",
     "Voir le profil"),
    ("heading=\"Ce que disent nos clients\"",
     "heading=\"Ce qu'en disent nos clients\""),
    ("sub=\"Des collaborations orientées résultats, avec des équipes B2B de tous secteurs.\"",
     "sub=\"Des collaborations orientées résultats, aux côtés d'équipes B2B de tous secteurs.\""),
    ("text: \"Nuvora a transformé notre présence LinkedIn. En six mois, 40% de nos prospects venaient de LinkedIn. Avant c'était un canal qu'on négligeait complètement.\"",
     "text: \"Nuvora a complètement changé notre présence LinkedIn. En six mois, 40 % de nos prospects venaient du canal. Avant, on le laissait dormir.\""),
    ("text: \"Ils ne se contentent pas de publier. Ils comprennent les cycles d'achat B2B. Les profils de nos dirigeants sont passés de dormants à générateurs de conversations entrantes.\"",
     "text: \"Ils ne se contentent pas de publier. Ils ont compris nos cycles d'achat B2B. Les profils de nos dirigeants sont passés de dormants à générateurs de conversations entrantes.\""),
    ("text: \"La transparence, c'est ce qui change tout. Chaque mois on voit exactement ce qui marche, ce qui marche pas, et où va le budget. Aucune autre agence nous avait donné ça.\"",
     "text: \"La transparence, voilà ce qui change tout. Chaque mois, on sait exactement ce qui fonctionne, ce qui cale et où passe le budget. Aucune autre agence ne nous avait donné ce niveau de lecture.\""),
    ("text: \"On a testé trois agences avant Nuvora. La différence ? Ils comprennent vraiment l'algorithme LinkedIn et comment les décideurs B2B se comportent sur la plateforme.\"",
     "text: \"On a essayé trois agences avant Nuvora. La différence ? Ils maîtrisent vraiment l'algorithme LinkedIn et la façon dont les décideurs B2B se comportent sur la plateforme.\""),
    ("text: \"Notre budget pub LinkedIn est passé de l'argent brûlé à des prospects qualifiés à moitié prix. L'architecture de campagne qu'ils ont construite est redoutablement efficace.\"",
     "text: \"Notre budget pub LinkedIn est passé du gouffre à des prospects qualifiés à moitié prix. L'architecture de campagne qu'ils ont posée est d'une efficacité redoutable.\""),
    ("text: \"Ce qui les distingue c'est la qualité du contenu. Chaque publication sonne comme nous, pas comme une agence. C'est rare quand on externalise du contenu B2B.\"",
     "text: \"Ce qui les distingue, c'est la qualité du contenu. Chaque publication a notre voix, pas celle d'une agence. C'est rare quand on externalise du contenu B2B.\""),
    ("text: \"De la stratégie à l'exécution, tout est pris en charge. On est passés d'une publication par mois à une vraie présence. Page entreprise, profils dirigeants, publicité. Et tout fonctionne.\"",
     "text: \"De la stratégie à l'exécution, ils prennent tout en main. On est passés d'une publication par mois à une vraie présence : page entreprise, profils dirigeants, publicité. Et tout l'écosystème tient debout.\""),
    ("text: \"Nuvora nous a aidés à monter un programme de mobilisation qui a transformé nos commerciaux en voix de référence. L'impact sur la prospection a été mesurable, et significatif.\"",
     "text: \"Nuvora nous a aidés à monter un programme d'employés ambassadeurs qui a transformé nos commerciaux en voix de référence. L'effet sur la prospection a été net et mesurable.\""),
    ("text: \"Ce qui m'a le plus impressionné c'est le suivi. De vrais indicateurs, de vrais chiffres de prospection. Pas des vues et des mentions « j'aime ». On sait enfin ce que LinkedIn apporte concrètement à notre activité.\"",
     "text: \"Ce qui m'a le plus impressionnée, c'est le pilotage. De vrais indicateurs commerciaux, des chiffres de prospection. Pas une liste de vues et de mentions j'aime. On sait enfin ce que LinkedIn apporte au business.\""),
])
